public enum Biome {
    RICH_CAVE, GENTLE_FOREST, CALMING_MEADOWS,
    CHILLY_TUNDRA, DUSTY_DESERT, MAGICAL_MUSHROOM_FOREST, HAUNTING_PLAGUELANDS,
    //DOWN BELOW IS FOR DRAGON EXPANSION!
    DRAGONS_MOUNTAIN_FOOT, DRAGONS_MOUNTAIN_RIDGE, DRAGONS_MOUNTAIN_SPUR,
    DRAGONS_MOUNTAIN_SHOULDER, DRAGONS_MOUNTAIN_PEAK, DRAGONS_DEN
}
