public enum Items
{
    //COMBAT
    SWORD, AXE, BOW, STAFF, TOME, FLAG, KNIFE, CLUB,

    //TOOLS                 V NOT IMPLEMENTED YET
    HAMMER, PICKAXE, HOE, BACKPACK,

    //ARMOUR ----- NO IMPLEMENTATION YET
    HELMET, ARMOUR, SHIELD
}
