public enum Resources
{
    // RESOURCES
    STONE, WOOD, FIBER, BONE, MUSHROOM, COPPER_ORE, COPPER_INGOT, TIN_ORE,
    TIN_INGOT, BRONZE_INGOT, IRON_ORE, IRON_INGOT, COAL, GOLD_ORE, GOLD,
    SILVER_ORE, SILVER_INGOT, SILVER_COINS
}
